// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiiX0fvNjss5kMoPINCmBGYcNcWT1WiOI',
    appId: '1:1027291256282:web:283d5243335bb97fa85ce3',
    messagingSenderId: '1027291256282',
    projectId: 'mypost-87ac4',
    authDomain: 'mypost-87ac4.firebaseapp.com',
    storageBucket: 'mypost-87ac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBAuJkQ8C2-b2GpxiGnqwALX8YSZYjY2k',
    appId: '1:1027291256282:android:5981cea5ffbd108ca85ce3',
    messagingSenderId: '1027291256282',
    projectId: 'mypost-87ac4',
    storageBucket: 'mypost-87ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPPyqWjaZKe4mXYzBgwsyrX7U0-mz6zQ',
    appId: '1:1027291256282:ios:8d34ba7219bca017a85ce3',
    messagingSenderId: '1027291256282',
    projectId: 'mypost-87ac4',
    storageBucket: 'mypost-87ac4.appspot.com',
    iosBundleId: 'com.example.bach1211',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPPyqWjaZKe4mXYzBgwsyrX7U0-mz6zQ',
    appId: '1:1027291256282:ios:a0ace31e8c18712fa85ce3',
    messagingSenderId: '1027291256282',
    projectId: 'mypost-87ac4',
    storageBucket: 'mypost-87ac4.appspot.com',
    iosBundleId: 'com.example.bach1211.RunnerTests',
  );
}
